name: Get Game Info

on:
  workflow_call:
  workflow_dispatch:

jobs:
  games_info:
    name: Get Game Info

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AmiiboGameList

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run
      working-directory: ./AmiiboGameList/bin/Debug/net8.0
      run: dotnet AmiiboGameList.dll

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: games_info
        path: ./AmiiboGameList/bin/Debug/net8.0/games_info.json
